/**
 * Demo 模式 Mock 数据
 * DEMO_MODE=true 时所有 API 返回此文件中的数据
 * 后续接真实 DB 时只需替换 API 路由中的数据源，结构完全不变
 */

import type { RouteDetail, RouteCard, TagItem, UserProfile, RouteStepDetail } from "@/types";

// ─────────────────────────────────────────────
// Mock 标签
// ─────────────────────────────────────────────
export const MOCK_TAGS: TagItem[] = [
  { id: "t1", name: "出片", category: "feature", icon: "📸" },
  { id: "t2", name: "小众", category: "feature", icon: "✨" },
  { id: "t3", name: "免费", category: "feature", icon: "🆓" },
  { id: "t4", name: "室内", category: "feature", icon: "🏛" },
  { id: "t5", name: "亲水", category: "atmosphere", icon: "💧" },
  { id: "t6", name: "文艺", category: "atmosphere", icon: "🎨" },
  { id: "t7", name: "自然", category: "atmosphere", icon: "🌿" },
  { id: "t8", name: "美食", category: "activity", icon: "🍜" },
  { id: "t9", name: "推车友好", category: "feature", icon: "🛻" },
  { id: "t10", name: "适合拍照", category: "feature", icon: "🌸" },
];

// ─────────────────────────────────────────────
// Mock 路线站点（复用）
// ─────────────────────────────────────────────
const DATE_STEPS_1: RouteStepDetail[] = [
  {
    id: "s1",
    sequence_order: 1,
    poi_name: "花港观鱼",
    stay_duration: 60,
    activity_tips: "从南门入，沿红鱼池漫步，春季海棠开得正好，适合慢走拍照。",
    photo_spots: "红鱼池边的垂柳倒影，石桥上两人并肩的背影。",
    transport_to_next: "walk",
    distance_to_next: 1200,
    time_to_next: 15,
    transport_tips: "沿苏堤南行约15分钟可到雷峰塔。",
    poi: {
      id: "p1",
      name: "花港观鱼",
      address: "杭州市西湖区南山路花港观鱼",
      latitude: 30.2278,
      longitude: 120.1312,
      category: "park",
      cover_image_url: null,
      avg_cost: 0,
      has_parking: false,
      has_restroom: true,
      is_accessible: true,
      amap_id: "B0FFH0WHHE",
    },
  },
  {
    id: "s2",
    sequence_order: 2,
    poi_name: "雷峰夕照观景台",
    stay_duration: 45,
    activity_tips: "登塔顶俯瞰西湖全景，傍晚时分光线最佳。票价20元/人，记得提前网上购票避免排队。",
    photo_spots: "塔顶西湖全景，夕阳倒映水面。",
    transport_to_next: "walk",
    distance_to_next: 800,
    time_to_next: 10,
    transport_tips: "步行穿过南山路到对面。",
    poi: {
      id: "p2",
      name: "雷峰塔",
      address: "杭州市西湖区南山路15号",
      latitude: 30.2319,
      longitude: 120.1487,
      category: "attraction",
      cover_image_url: null,
      avg_cost: 20,
      has_parking: false,
      has_restroom: true,
      is_accessible: true,
      amap_id: "B0FFHXRV0W",
    },
  },
  {
    id: "s3",
    sequence_order: 3,
    poi_name: "湖滨晴雨·茶餐厅",
    stay_duration: 90,
    activity_tips: "湖景卡座需提前1天预约，点龙井虾仁和东坡肉，均价人均120元左右。",
    photo_spots: "落地窗外西湖夜景，食物摆盘精致可拍。",
    transport_to_next: "walk",
    distance_to_next: 0,
    time_to_next: 0,
    transport_tips: "",
    poi: {
      id: "p3",
      name: "湖滨晴雨",
      address: "杭州市上城区湖滨路1号",
      latitude: 30.2425,
      longitude: 120.1523,
      category: "restaurant",
      cover_image_url: null,
      avg_cost: 120,
      has_parking: false,
      has_restroom: true,
      is_accessible: true,
      amap_id: null,
    },
  },
];

const KIDS_STEPS_1: RouteStepDetail[] = [
  {
    id: "k1",
    sequence_order: 1,
    poi_name: "杭州植物园",
    stay_duration: 90,
    activity_tips: "竹类区和草坪区适合小孩奔跑，2岁以上可以认识各种植物，带上零食在草坪野餐体验很好。",
    photo_spots: "竹林小径，孩子在大草坪奔跑的背影。",
    transport_to_next: "drive",
    distance_to_next: 4500,
    time_to_next: 15,
    transport_tips: "开车或打车到下一站，路程约4.5公里。",
    poi: {
      id: "k_p1",
      name: "杭州植物园",
      address: "杭州市西湖区玉泉路1号",
      latitude: 30.2564,
      longitude: 120.1198,
      category: "park",
      cover_image_url: null,
      avg_cost: 10,
      has_parking: true,
      has_restroom: true,
      is_accessible: true,
      amap_id: "B0FFHOP5YQ",
    },
  },
  {
    id: "k2",
    sequence_order: 2,
    poi_name: "杭州自然博物探索馆",
    stay_duration: 120,
    activity_tips: "4-8岁孩子最喜欢的恐龙展厅和动物标本区，互动性强。需提前在公众号预约门票，免费入场。",
    photo_spots: "恐龙骨架前，孩子张嘴模仿恐龙的表情。",
    transport_to_next: "drive",
    distance_to_next: 3000,
    time_to_next: 12,
    transport_tips: "开车约12分钟到午餐地点。",
    poi: {
      id: "k_p2",
      name: "杭州自然博物探索馆",
      address: "杭州市西湖区玉皇山路6号",
      latitude: 30.2278,
      longitude: 120.1456,
      category: "museum",
      cover_image_url: null,
      avg_cost: 0,
      has_parking: true,
      has_restroom: true,
      is_accessible: true,
      amap_id: null,
    },
  },
  {
    id: "k3",
    sequence_order: 3,
    poi_name: "绿茶餐厅·西湖店",
    stay_duration: 75,
    activity_tips: "儿童菜式选择多，价格适中，人均60元。高峰期等位约30分钟，建议11:30前到。",
    photo_spots: "餐厅竹林装饰背景。",
    transport_to_next: "walk",
    distance_to_next: 0,
    time_to_next: 0,
    transport_tips: "",
    poi: {
      id: "k_p3",
      name: "绿茶餐厅·西湖店",
      address: "杭州市西湖区清波街道龙井路1号",
      latitude: 30.2349,
      longitude: 120.1334,
      category: "restaurant",
      cover_image_url: null,
      avg_cost: 60,
      has_parking: false,
      has_restroom: true,
      is_accessible: true,
      amap_id: null,
    },
  },
];

// ─────────────────────────────────────────────
// Mock 路线详情数据
// ─────────────────────────────────────────────
export const MOCK_ROUTES: RouteDetail[] = [
  {
    id: "route-001",
    title: "西湖半日慢游约会路线",
    subtitle: "花港→雷峰塔→湖边晚餐，3小时走完最美西湖",
    scene: "date",
    city: "杭州",
    duration_type: "half",
    duration_minutes: 210,
    budget_per_person: 150,
    cover_image_url: "https://images.unsplash.com/photo-1504893524553-b855bce32c67?w=800&q=80",
    avg_rating: 4.8,
    favorite_count: 312,
    view_count: 2841,
    stop_count: 3,
    weather_type: "sunny",
    is_featured: true,
    tags: [MOCK_TAGS[0], MOCK_TAGS[9], MOCK_TAGS[5]],
    is_favorited: false,
    description:
      "这条路线把西湖最经典的几个节点串起来，又不会走得太累。花港观鱼适合慢逛，红鱼池边的垂柳和游鱼是很好的拍照背景；雷峰塔建议傍晚去，光线最好，但要提前网上购票；最后在湖边餐厅收尾，卡座需要提前一天预约。整条路线步行为主，两个人走下来大概3.5小时。",
    highlights: ["花港观鱼免费，春季海棠绝美", "雷峰塔日落视角是整条路线高光时刻", "湖景餐厅提前订座体验完整"],
    tips: [
      "雷峰塔网上购票比现场便宜，且可跳过排队",
      "湖滨晴雨卡座需提前1天电话预约，周末更早",
      "花港停车位极少，建议坐公交或打车",
      "全程约5公里，穿舒适的鞋",
    ],
    rainy_alternative: "雨天可改去西湖博物馆+茶叶博物馆，室内为主，同样有氛围。",
    suggested_start_time: "15:00",
    fit_for: ["情侣约会", "纪念日", "第一次来杭州的朋友"],
    not_fit_for: ["不喜欢走路的人（全程约5公里）", "带婴儿推车（部分路段有台阶）"],
    risk_notes: ["节假日花港人多，建议工作日或早上9点前", "雷峰塔排队高峰在14-16点"],
    kid_age_min: null,
    kid_age_max: null,
    stroller_friendly: false,
    has_restroom: true,
    has_nursing_room: false,
    has_parking: false,
    has_dining: true,
    steps: DATE_STEPS_1,
    images: [
      { id: "img1", image_url: "https://images.unsplash.com/photo-1504893524553-b855bce32c67?w=800&q=80", caption: "花港观鱼春色", sort_order: 0, is_cover: true },
      { id: "img2", image_url: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800", caption: "雷峰塔夕照", sort_order: 1, is_cover: false },
    ],
    published_at: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "route-002",
    title: "拱墅运河文艺半日游",
    subtitle: "小河直街+桥西历史街区，市井气息中的约会体验",
    scene: "date",
    city: "杭州",
    duration_type: "half",
    duration_minutes: 180,
    budget_per_person: 80,
    cover_image_url: "https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&q=80",
    avg_rating: 4.6,
    favorite_count: 187,
    view_count: 1523,
    stop_count: 3,
    weather_type: "both",
    is_featured: true,
    tags: [MOCK_TAGS[1], MOCK_TAGS[5], MOCK_TAGS[0]],
    is_favorited: false,
    description:
      "运河边这条线路很少出现在攻略里，但本地人都知道。小河直街保留了老杭州的生活气息，咖啡馆和手工艺店散落其中；桥西历史街区有几家设计感不错的独立餐厅。整体人不多，适合两个人安静地逛逛聊聊。",
    highlights: ["小众不拥挤，周末也能安静走完", "独立咖啡馆质量高，适合坐下来聊天", "运河沿岸夜景值得留到天黑"],
    tips: [
      "桥西历史街区部分商铺周一不营业，建议提前查好",
      "小河直街咖啡馆推荐「谁最中国」，但周末可能需要等位",
      "运河游船傍晚6点后有夜游班次，可作为收尾体验",
    ],
    rainy_alternative: "雨天运河边更有意境，带伞即可；或改去附近的桥西直街有顶的廊道段。",
    suggested_start_time: "14:00",
    fit_for: ["喜欢文艺市井风格的情侣", "不想人挤人的本地人"],
    not_fit_for: ["希望打卡热门景点的游客", "对老旧街区审美无感的人"],
    risk_notes: ["部分路段地面不平整，注意脚下"],
    kid_age_min: null,
    kid_age_max: null,
    stroller_friendly: true,
    has_restroom: true,
    has_nursing_room: false,
    has_parking: true,
    has_dining: true,
    steps: [],
    images: [
      { id: "img3", image_url: "https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&q=80", caption: "运河边街景", sort_order: 0, is_cover: true },
    ],
    published_at: "2026-03-05T00:00:00.000Z",
  },
  {
    id: "route-003",
    title: "植物园+博物馆亲子全日路线",
    subtitle: "适合2-8岁，推车友好，含午餐推荐",
    scene: "kids",
    city: "杭州",
    duration_type: "full",
    duration_minutes: 360,
    budget_per_person: 80,
    cover_image_url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&q=80",
    avg_rating: 4.7,
    favorite_count: 256,
    view_count: 3102,
    stop_count: 3,
    weather_type: "sunny",
    is_featured: true,
    tags: [MOCK_TAGS[8], MOCK_TAGS[6], MOCK_TAGS[7]],
    is_favorited: false,
    description:
      "这条路线专为2-8岁孩子设计，全程推车可达，三个站点节奏合理不赶。植物园的大草坪让孩子尽情跑，博物馆的恐龙展让4岁以上孩子兴奋，绿茶餐厅儿童友好且价格适中。全天下来孩子累了家长也满足了。",
    highlights: ["三站均有停车场，开车家庭最方便", "植物园大草坪是杭州最好的野餐地之一", "自然博物馆免费且互动性强"],
    tips: [
      "自然博物馆需提前在公众号预约，免费但名额有限",
      "绿茶餐厅高峰期等位30分钟，11:30前到可省去等待",
      "植物园停车场节假日满员较快，建议9点前到",
      "全程备好湿巾和换洗衣物",
    ],
    rainy_alternative: "雨天取消植物园，改为上午直接去博物馆+下午杭州儿童剧场看演出。",
    suggested_start_time: "09:30",
    fit_for: ["2-8岁孩子的家庭", "喜欢自然科学的孩子", "需要大量活动空间消耗精力的小孩"],
    not_fit_for: ["0-1岁婴儿（博物馆刺激太强）", "雨天（植物园部分区域泥泞）"],
    risk_notes: ["植物园水边要注意孩子安全", "博物馆人多时注意看管孩子"],
    kid_age_min: 2,
    kid_age_max: 8,
    stroller_friendly: true,
    has_restroom: true,
    has_nursing_room: true,
    has_parking: true,
    has_dining: true,
    steps: KIDS_STEPS_1,
    images: [
      { id: "img5", image_url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&q=80", caption: "孩子在草坪奔跑", sort_order: 0, is_cover: true },
    ],
    published_at: "2026-03-08T00:00:00.000Z",
  },
  {
    id: "route-004",
    title: "良渚文化村亲子半日游",
    subtitle: "博物馆+村民食堂+玉鸟集，历史与生活感并存",
    scene: "kids",
    city: "杭州",
    duration_type: "half",
    duration_minutes: 240,
    budget_per_person: 100,
    cover_image_url: "https://images.unsplash.com/photo-1554907984-15263bfd63bd?w=800&q=80",
    avg_rating: 4.5,
    favorite_count: 198,
    view_count: 2201,
    stop_count: 3,
    weather_type: "both",
    is_featured: false,
    tags: [MOCK_TAGS[3], MOCK_TAGS[8], MOCK_TAGS[6]],
    is_favorited: false,
    description:
      "良渚博物院对孩子来说是一次很好的历史启蒙，展陈设计对孩子友好，有互动区域。玉鸟集是文化村里的商业街，餐饮和文创都不错，路面平整推车无障碍。整体节奏轻松，适合全家慢慢逛。",
    highlights: ["良渚博物院是世界文化遗产，寓教于乐", "全程路面平整，推车非常方便", "玉鸟集有儿童书店和手作体验"],
    tips: [
      "良渚博物院免费，但节假日需提前网上预约",
      "从市区开车约40分钟，建议错开早高峰",
      "玉鸟集餐厅午市12-14点人多，建议11:30或14:00后",
    ],
    rainy_alternative: "雨天全程室内（博物院+玉鸟集），完全不受影响。",
    suggested_start_time: "10:00",
    fit_for: ["3-10岁孩子", "对历史文化感兴趣的家庭", "雨天出行"],
    not_fit_for: ["2岁以下婴幼儿（展览内容较复杂）"],
    risk_notes: ["节假日博物院人多，提前预约是关键"],
    kid_age_min: 3,
    kid_age_max: 10,
    stroller_friendly: true,
    has_restroom: true,
    has_nursing_room: true,
    has_parking: true,
    has_dining: true,
    steps: [],
    images: [
      { id: "img7", image_url: "https://images.unsplash.com/photo-1554907984-15263bfd63bd?w=800&q=80", caption: "良渚博物院", sort_order: 0, is_cover: true },
    ],
    published_at: "2026-03-10T00:00:00.000Z",
  },
  {
    id: "route-005",
    title: "南宋御街夜间约会路线",
    subtitle: "中山路+清河坊，老杭州夜晚的另一面",
    scene: "date",
    city: "杭州",
    duration_type: "short",
    duration_minutes: 120,
    budget_per_person: 60,
    cover_image_url: "https://images.unsplash.com/photo-1519608487953-e999c86e7455?w=800&q=80",
    avg_rating: 4.4,
    favorite_count: 142,
    view_count: 1876,
    stop_count: 2,
    weather_type: "both",
    is_featured: false,
    tags: [MOCK_TAGS[1], MOCK_TAGS[5], MOCK_TAGS[0]],
    is_favorited: false,
    description:
      "这条线路专为晚上设计，中山路的灯光夜景比白天更有氛围，清河坊的小吃边走边吃，2小时体量轻巧，适合平时约会的快速选项。",
    highlights: ["夜晚灯光氛围比白天更好", "2小时短线，工作日晚上也能走", "清河坊小吃边走边吃很放松"],
    tips: ["清河坊部分摊位21:00后陆续收摊，建议19:30前到", "中山路路边停车位少，建议附近停车场"],
    rainy_alternative: "雨天中山路有骑楼遮雨，小雨可以正常进行。",
    suggested_start_time: "19:00",
    fit_for: ["工作日晚上约会", "想要轻松不累的两人时光"],
    not_fit_for: ["希望白天出行的用户"],
    risk_notes: ["节假日清河坊人流量大，推荐工作日"],
    kid_age_min: null,
    kid_age_max: null,
    stroller_friendly: false,
    has_restroom: true,
    has_nursing_room: false,
    has_parking: true,
    has_dining: true,
    steps: [],
    images: [
      { id: "img9", image_url: "https://images.unsplash.com/photo-1519608487953-e999c86e7455?w=800&q=80", caption: "南宋御街夜景", sort_order: 0, is_cover: true },
    ],
    published_at: "2026-03-12T00:00:00.000Z",
  },
  {
    id: "route-006",
    title: "西溪湿地遛娃全日游",
    subtitle: "划船+草地+儿童活动区，0-6岁都适合",
    scene: "kids",
    city: "杭州",
    duration_type: "full",
    duration_minutes: 300,
    budget_per_person: 120,
    cover_image_url: "https://images.unsplash.com/photo-1523712999610-f77fbcfc3843?w=800&q=80",
    avg_rating: 4.6,
    favorite_count: 223,
    view_count: 2654,
    stop_count: 3,
    weather_type: "sunny",
    is_featured: false,
    tags: [MOCK_TAGS[4], MOCK_TAGS[6], MOCK_TAGS[8]],
    is_favorited: false,
    description:
      "西溪湿地面积大，但亲子路线只需走核心区域。租一条电瓶船让孩子近距离看鸟和水生植物，之后在秋雪庵区域的草地野餐，傍晚在儿童活动区收尾，节奏完整不赶。",
    highlights: ["电瓶船是孩子最喜欢的环节", "草地野餐区域宽阔适合奔跑", "儿童活动区设施新且安全"],
    tips: [
      "湿地门票80元，电瓶船另付费约30元/艘",
      "野餐食物可自带或在园内餐厅购买",
      "推车可进大部分区域，但船上需抱着孩子",
      "夏季蚊虫较多，带好驱蚊液",
    ],
    rainy_alternative: "雨天取消，改为室内亲子场所。",
    suggested_start_time: "09:00",
    fit_for: ["0-6岁孩子的家庭", "喜欢自然环境的家庭", "需要大空间活动的孩子"],
    not_fit_for: ["雨天（户外为主）", "对自然环境过敏的孩子"],
    risk_notes: ["水边务必看管孩子", "夏天高温建议上午出行"],
    kid_age_min: 0,
    kid_age_max: 6,
    stroller_friendly: true,
    has_restroom: true,
    has_nursing_room: true,
    has_parking: true,
    has_dining: true,
    steps: [],
    images: [
      { id: "img11", image_url: "https://images.unsplash.com/photo-1523712999610-f77fbcfc3843?w=800&q=80", caption: "西溪湿地", sort_order: 0, is_cover: true },
    ],
    published_at: "2026-03-15T00:00:00.000Z",
  },
];

// ─────────────────────────────────────────────
// Mock 用户
// ─────────────────────────────────────────────
export const MOCK_USER: UserProfile = {
  id: "demo-user-001",
  email: "demo@zoudi.app",
  nickname: "演示用户",
  avatar_url: null,
  city: "杭州",
  is_admin: false,
  created_at: "2026-03-01T00:00:00.000Z",
  preferences: {
    primary_scene: "date",
    budget_level: "medium",
    kid_age_min: null,
    kid_age_max: null,
    prefer_duration: "half",
  },
};

export const MOCK_ADMIN_USER: UserProfile = {
  id: "demo-admin-001",
  email: "admin@zoudi.app",
  nickname: "管理员",
  avatar_url: null,
  city: "杭州",
  is_admin: true,
  created_at: "2026-03-01T00:00:00.000Z",
  preferences: null,
};

// ─────────────────────────────────────────────
// Mock 搜索热词
// ─────────────────────────────────────────────
export const MOCK_HOTWORDS = [
  "西湖约会", "遛娃推车", "雨天路线", "免费景点", "亲子半日游",
];

// ─────────────────────────────────────────────
// 工具函数：路线 → RouteCard（去掉详情字段）
// ─────────────────────────────────────────────
export function toRouteCard(r: RouteDetail): RouteCard {
  return {
    id: r.id,
    title: r.title,
    subtitle: r.subtitle,
    scene: r.scene,
    city: r.city,
    duration_type: r.duration_type,
    duration_minutes: r.duration_minutes,
    budget_per_person: r.budget_per_person,
    cover_image_url: r.cover_image_url,
    avg_rating: r.avg_rating,
    favorite_count: r.favorite_count,
    stop_count: r.stop_count,
    weather_type: r.weather_type,
    is_featured: r.is_featured,
    tags: r.tags,
    is_favorited: r.is_favorited,
  };
}

// ─────────────────────────────────────────────
// Demo 模式判断
// ─────────────────────────────────────────────
export function isDemoMode(): boolean {
  return process.env.DEMO_MODE === "true";
}
